### PR TITLE
[UX] Allow users to copy stuff inside a post

### PR DESCRIPTION
**Pull request by NobreHD**
Yet again untested code, but it should work. Might need some work for the CSS

### CODE REVIEW

**Comment by GStudiosX2** [comment]
> Yet again untested code, but it should work. Might need some work for the CSS

What browser are you using it works fine for me ?

**Comment by NobreHD** [comment]
> > Yet again untested code, but it should work. Might need some work for the CSS
> 
> What browser are you using it works fine for me ?
Arc (Chromium). It has been reported by other users on Discord and Lyntr

**Comment by GStudiosX2** [comment]
> > > Yet again untested code, but it should work. Might need some work for the CSS
> > 
> > What browser are you using it works fine for me ?
> Arc (Chromium). It has been reported by other users on Discord and Lyntr
> 

Must be something with Arc I can copy stuff fine

**Comment by NobreHD** [comment]
> > > Yet again untested code, but it should work. Might need some work for the CSS
> > 
> > What browser are you using it works fine for me ?
> > Arc (Chromium). It has been reported by other users on Discord and Lyntr
> 
> Must be something with Arc I can copy stuff fine
Let me run a battery of tests (Edge, Chrome, Firefox, Brave and OperaGX)

**Comment by GStudiosX2** [comment]
Ok never mind it doesn't work on desktop only mobile

**Comment by GStudiosX2** [comment]
> Yet again untested code, but it should work. Might need some work for the CSS

Just tested it does work you might want to change the cursor to pointer on them though but probably should wait for faces review

**Comment by face-hh** [comment]
Would probably be best to enable the ability to select text on the comment side on the right, on the parent lynt. And also include a "Copy" button in the dropdown (below the Report button)

**Comment by NobreHD** [comment]
> Would probably be best to enable the ability to select text on the comment side on the right, on the parent lynt. And also include a "Copy" button in the dropdown (below the Report button)

So, I added the copy button above the reports because it's something that people will use more than the reports.

About the text selection, since post are using a generalized element (`Lynt.svelte`), adding that would be needlessly harder than just adding a class just to add the pointer back.

**Pull request merged**
