### PR TITLE
feat: add support for links

### PR DESCRIPTION
**Pull request by RealPacket**
Hopefully this doesn't have any XSS vulnerabilities, but I don't think so.

### CODE REVIEW

**Comment by RealPacket** [comment]
Preview:

https://github.com/user-attachments/assets/ebd5172e-ad10-448f-9808-091497bafe49

**Comment by GStudiosX2** [comment]
How did you get dompurify to work usually I have to use isomorphic-dompurify with sveltekit

**Comment by GStudiosX2** [comment]
Oh you run it client side

**Comment by RealPacket** [comment]
I'm going to add support for @-mentioning too.

**Comment by GStudiosX2** [comment]
> I'm going to add support for @-mentioning too.

Ok just don't add anything that's in my repo right now because I'm gonna pr it when it's done

**Comment by RealPacket** [comment]
> > I'm going to add support for @-mentioning too.
> 
> Ok just don't add anything that's in my repo right now because I'm gonna pr it when it's done
> 
> Edit: ~I might make the pr right now as a draft~ #20

don't worry. It's 10:30 PM and I'm going to have to go to sleep at some point.

**Comment by face-hh** [comment]
A popup notifying the user that they're going off-site is needed.

**Comment by RealPacket** [comment]
> A popup notifying the user that they're going off-site is needed.

Oh. Although I think if you're clicking the link then it should be obvious that you're going off-site. Will add.

**Comment by RealPacket** [comment]
I do need to sync my branches with upstream though.

**Comment by RealPacket** [comment]
I don't know how I'm going to use the `AlertDialog` in the script but I'll probably use a hack to make it work.

**Comment by RealPacket** [comment]
> I don't know how I'm going to use the `AlertDialog` in the script but I'll probably use a hack to make it work.

Actually, I don't think I need a hack to make it work. Just wrap a AlertDialog within a #if that only resolves to true when the user is about to click an external link.

**Comment by RealPacket** [comment]
Nevermind, I have just settled for a separate page which has the URL and presents a dialog which asks the user if they want to go to the link.

**Comment by RealPacket** [comment]
> A popup notifying the user that they're going off-site is needed.

I've added it, however, I need to add styling because it looks ugly as hell

**Comment by face-hh** [comment]
Use the AlertDialog built

**Comment by RealPacket** [comment]
> Use the AlertDialog built

I tried, it never showed up on the page.

**Comment by face-hh** [comment]
Check how it was done for the previous dialogues. You simply have to do `bind:open={redirect}" and change redirect to true whenever you want to show the dialogue

**Comment by RealPacket** [comment]
> Check how it was done for the previous dialogues. You simply have to do `bind:open={redirect}" and change redirect to true whenever you want to show the dialogue

Oh.

**Comment by RealPacket** [comment]
> Check how it was done for the previous dialogues. You simply have to do `bind:open={redirect}" and change redirect to true whenever you want to show the dialogue

The problem is that I modify the HTML directly. I don't think that would work with my current idea.

**Comment by face-hh** [comment]
Just checked the code. You probably could do this without modifying the HTML directly.

But if not, attach a on:click on the <a> and do preventDefault. Intercept the content of the clicked <a>, and trigger the alert with the URL in the contents to let the user know they're going off-site.

**Comment by RealPacket** [comment]
No wonder why the Alert Dialog wasn't popping up, I have to set the `open` property on the root for some reason too!

**Comment by RealPacket** [comment]
Only problem is... Yeah, I don't think I'd want `open=false` or `open=true` near every element.
Also moves the text and stuff so... No?
image

**Comment by RealPacket** [comment]
image
Man, I wonder why? It wouldn't be because I accidentally added open=false after the end of the /if statement!

**Comment by RealPacket** [comment]
> A popup notifying the user that they're going off-site is needed.

I have *almost* implemented that, the only thing that might prevent it from being merged is that when you click a link and then click it again it doesn't work because I stopped propagation to stop the page from refreshing.

**Comment by RealPacket** [comment]
image
Why!?!??!

**Comment by RealPacket** [comment]
> image Why!?!??!

That usually happens when I click another link

**Comment by RealPacket** [comment]
> > image Why!?!??!
> 
> That usually happens when I click another link

for some reason I can't get it to happen again

**Comment by RealPacket** [comment]
For now, I'll just let it refresh the page, because it'll still have the popup anyways

**Comment by RealPacket** [comment]
image
I got it again

**Comment by RealPacket** [comment]
The same bug happens to the #21

**Comment by face-hh** [comment]
Fixes #52

**Comment by GStudiosX2** [comment]
Since this was merged 
Screenshot_20240809-110640
This has been happening it could be a different pr though because face merged multiple but I think it's most likely this one

**Pull request merged**
