### PR TITLE
Add Syndication (e.g. RSS, Atom, JSON Feed) support

### PR DESCRIPTION
**Pull request by RealPacket**
I plan on adding Syndication support for this, so you can plug this into a reader (like Newsflash, you can find it in Flathub, it's a GTK+ and libadwaita app for consuming Syndication formats (e.g. RSS, Atom, JSON Feed)).

- [ ] Ready for review
  - [ ] Output passes W3C validator: https://validator.w3.org/feed/check.cgi
  - [ ] RSS feed channels
    - [ ] User-specific channels
    - [ ] Your feed (For you, following, etc).

### CODE REVIEW

**Comment by RealPacket** [comment]
image
It generates! ...But it doesn't properly generate some things

**Comment by GStudiosX2** [comment]
What is RSS ?

**Comment by inventionpro** [comment]
> What is RSS ?

stands for "Really Simple Syndication" its a xml formatted and used to distribute frequently updated content
Wikipedia: https://en.wikipedia.org/wiki/RSS

**Comment by RealPacket** [comment]
Currently, this is what the RSS looks like on my testing fork.
image

**Comment by GStudiosX2** [comment]
> Currently, this is what the RSS looks like on my testing fork. image

Screenshot_20240803-185147
Works (I added images)

**Comment by RealPacket** [comment]
I was thinking about images too

**Comment by RealPacket** [comment]
I added a link to the feed on the profile. Here's what it looks like:
image

**Comment by RealPacket** [comment]
> > Currently, this is what the RSS looks like on my testing fork. image
> 
> Screenshot_20240803-185147 Works (I also added images)

Also, I have no idea why you're using Android for this, and also, how are you accessing the server via Android? Did you get the IP of your PC on LAN or use something like UserLAnd (I've never used it but I've heard of it)?

**Comment by RealPacket** [comment]
> > > Currently, this is what the RSS looks like on my testing fork. image
> > 
> > 
> > Screenshot_20240803-185147 Works (I also added images)
> 
> Also, I have no idea why you're using Android for this, and also, how are you accessing the server via Android? Did you get the IP of your PC on LAN or use something like UserLAnd (I've never used it but I've heard of it)?

...Unless you host your own server on a VPS or something

**Comment by GStudiosX2** [comment]
> > > Currently, this is what the RSS looks like on my testing fork. image
> > 
> > Screenshot_20240803-185147 Works (I also added images)
> 
> Also, I have no idea why you're using Android for this, and also, how are you accessing the server via Android? Did you get the IP of your PC on LAN or use something like UserLAnd (I've never used it but I've heard of it)?
> ...Unless if you host your fork on a VPS or something.

I'm using termux + proot-distro I couldn't actually use localhost in the app I used to look at the RSS feed and had to use ngrok

**Comment by face-hh** [comment]
I doubt RSS feeds will work with our current Cloudflare setup.

**Comment by RealPacket** [comment]
> I doubt RSS feeds will work with our current Cloudflare setup.

I don't test with cloudflare because I run my testing Lyntr instance locally

**Comment by face-hh** [comment]
Sorry, but I'll mark this as 'not planned' for now. The effort required to make this work with our current configuration outweighs the potential benefits.

**Pull request closed without merging**
