### PR TITLE
Fix a few issues in the new mobile UI and misc

### PR DESCRIPTION
**Pull request by GStudiosX2**

### CODE REVIEW

**Comment by GStudiosX2** [comment]
Wait don't merge yet forgot one thing

**Comment by GStudiosX2** [comment]
Ok now it can be merged

**Comment by GStudiosX2** [comment]
Ok now it should be safe

**Comment by face-hh** [comment]
Oh crap I didn't see this before fixing the desktop css myself. Could you fix the conflicts? They shouldn't be too major

**Comment by GStudiosX2** [comment]
> Oh crap I didn't see this before fixing the desktop css myself. Could you fix the conflicts? They shouldn't be too major

The conflicts should be fixed

**Comment by face-hh** [comment]
The like, comment and repost count seems to not work properly. It should have less spacing and have the coloring effect apply to them.
like counter

Also you created https://lyntr.com/test because of `routes/test/+page.svelte`

**Comment by GStudiosX2** [comment]
> The like, comment and repost count seems to not work properly. It should have less spacing and have the coloring effect apply to them. like counter [ like counter ](https://private-user-images.githubusercontent.com/69168154/352931101-ac493448-a87a-4f5d-848c-98c637f82d1b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMzM1NzIsIm5iZiI6MTcyMjIzMzI3MiwicGF0aCI6Ii82OTE2ODE1NC8zNTI5MzExMDEtYWM0OTM0NDgtYTg3YS00ZjVkLTg0OGMtOThjNjM3ZjgyZDFiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDA2MDc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkNWVmYmNjM2JhM2IyMmExMWM0MDVhZWUxYzliMjY0OWVlZmE4OTFiZDE0Y2I1YWI3NGYwMWU5ZTg3OGU2NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q1vNKcYGzXl8PFQclx-OisEDiQQrVDwLbReah5_KqLY) [ ](https://private-user-images.githubusercontent.com/69168154/352931101-ac493448-a87a-4f5d-848c-98c637f82d1b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMzM1NzIsIm5iZiI6MTcyMjIzMzI3MiwicGF0aCI6Ii82OTE2ODE1NC8zNTI5MzExMDEtYWM0OTM0NDgtYTg3YS00ZjVkLTg0OGMtOThjNjM3ZjgyZDFiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDA2MDc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkNWVmYmNjM2JhM2IyMmExMWM0MDVhZWUxYzliMjY0OWVlZmE4OTFiZDE0Y2I1YWI3NGYwMWU5ZTg3OGU2NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q1vNKcYGzXl8PFQclx-OisEDiQQrVDwLbReah5_KqLY)
> 
> Also you created https://lyntr.com/test because of `routes/test/+page.svelte`

What coloring effect ? Oops did I accidentally push test

**Comment by face-hh** [comment]
This now has a small conflict because of #7

**Comment by GStudiosX2** [comment]
> This now has a small conflict because of #7

I fixed the conflict

**Comment by face-hh** [comment]
image
It seems to now affect popups too. Also I think the drop shadow (or the button entirely) should get a higher z-index since it's being cut off by the lynt card

**Comment by face-hh** [comment]
Visual of the last sentence:
image

**Comment by GStudiosX2** [comment]
> image It seems to now affect popups too. Also I think the drop shadow (or the button entirely) should get a higher z-index since it's being cut off by the lynt card

I forgot about the popovers lol I moved the effect up a few elements so it affected it too it getting cut off might be overflow on the post

**Comment by GStudiosX2** [comment]
I can't get rid of the overflow hidden though overwise stuff overflows

**Comment by GStudiosX2** [comment]
Screenshot_20240729-080512

**Pull request merged**
